version: '3.9'

services:
  server:
    build: .
    ports:
      - 5000:5000
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432 

volumes:
  data: